defaults: &defaults
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000

development:
  database: bank_development
  <<: *defaults

test:
  database: bank_test
  <<: *defaults

production:
  database: bank_test
  <<: *defaults